services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: sms-convenios-api
    env_file:
      - ./Api/.env
    ports:
      - '5211:5210' # ajuste conforme a porta da sua API
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - apparmor=unconfined
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge
